version: '3'
services:
  redis:
    image: redis:latest
  postgres:
    image: postgres:11.6
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    build: ./
    command: >
      bash -c "./manage.py wait_for_postgres &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
  documentation:
    restart: always
    build: ./
    command: "mkdocs serve"
    volumes:
      - ./:/app
    ports:
      - "8001:8001"
